language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements_dev.txt"
# before script run flake8
before_script: flake8 .
# command to run tests
script: py.test
